version: '2'

services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - ./mysql-datavolume:/var/lib/mysql
    ports:
      - 3306:3306

  tor:
    container_name: tor
    restart: always
    hostname: tor
    image: osminogin/tor-simple

  bot:
    container_name: bot
    hostname: bot
    build:
      context: .
    environment:
      WEB_EXTRACTOR_SOURCE: exchangeratesapi.io
      WEB_EXTRACTOR_TIMEOUT: 5
      DATABASE_SQLALCHEMY_URL: mysql+pymysql://${SQL_USER}:${SQL_PASSWORD}@db:3306/${SQL_DATABASE}
      CACHE_TIMEOUT: 600
      BASE_CURRENCY: USD
      TELEGRAM_PROXY: socks5://tor:9050
